-- MySQL Script generated by MySQL Workbench
-- Tue Apr  7 23:16:12 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema empresa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema empresa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `empresa` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `empresa` ;

-- -----------------------------------------------------
-- Table `empresa`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa`.`Clientes` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `cedula` VARCHAR(45) NULL,
  `rif` VARCHAR(45) NULL,
  `direccion` INT NULL,
  `telefono` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa`.`Direcciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa`.`Direcciones` (
  `id` INT NOT NULL,
  `cliente_id` INT NOT NULL,
  `avenida` VARCHAR(45) NULL,
  `calle` VARCHAR(45) NULL,
  `urb` VARCHAR(45) NULL,
  `sector` VARCHAR(45) NULL,
  `edificio` VARCHAR(45) NULL,
  `piso` VARCHAR(45) NULL,
  `apartamento` VARCHAR(45) NULL,
  `numero_de_casa` VARCHAR(45) NULL,
  `ciudad` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `cliente_id`),
  INDEX `cliente_id_idx` (`cliente_id` ASC),
  CONSTRAINT `cliente_id`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `empresa`.`Clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa`.`Categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa`.`Categorias` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa`.`Productos` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `precio` DECIMAL(2) NULL,
  `stock` INT NULL,
  `categoria` INT NOT NULL,
  PRIMARY KEY (`id`, `categoria`),
  INDEX `categoria_id_idx` (`categoria` ASC),
  CONSTRAINT `categoria_id`
    FOREIGN KEY (`categoria`)
    REFERENCES `empresa`.`Categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa`.`Facturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa`.`Facturas` (
  `id` INT NOT NULL,
  `cliente_id` INT NOT NULL,
  `fecha` DATETIME NULL,
  `factura_productos_id` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `cliente_id`),
  INDEX `fk_Facturas_Clientes1_idx` (`cliente_id` ASC),
  CONSTRAINT `cliente_id`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `empresa`.`Clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa`.`Facturas_Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa`.`Facturas_Productos` (
  `id` INT NOT NULL,
  `factura_id` INT NOT NULL,
  `producto_id` INT NULL,
  `cantidad` VARCHAR(45) NULL,
  `total` DECIMAL(2) NULL,
  PRIMARY KEY (`id`, `factura_id`),
  INDEX `fk_Facturas_Productos_Facturas1_idx` (`factura_id` ASC),
  INDEX `fk_Facturas_Productos_Productos1_idx` (`producto_id` ASC),
  CONSTRAINT `factura_id`
    FOREIGN KEY (`factura_id`)
    REFERENCES `empresa`.`Facturas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `producto_id`
    FOREIGN KEY (`producto_id`)
    REFERENCES `empresa`.`Productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
